### ISSUE TITLE
Depend on latest TeraMath instead of engine for Matrix4i

### ISSUE THREAD

**Issue by Cervator** [Terasology/GrammarSystem#3]
The Matrix4i class was moved.

Depends on https://github.com/MovingBlocks/Terasology/issues/2093 and for a new TeraMath release to actually include it (code is there just not released)

**Comment by Cervator** [comment]
Bump - the new TeraMath is now available for use.

@skaldarnar - hiiiii! :D

**Comment by skaldarnar** [comment]
`master` is working again (probably not in multiplayer though).
